export type Category = {
  id: string;
  title: string;
  subtitle: string;
  icon: string;
  color: string;
};
export type Location = {
  city: string;
  slug: string;
  locality: string;
  pincode: string;
  state: string;
  lat: number;
  lng: number;
};
export type Job = {
  id: string;
  slug: string;
  title: string;
  company: string;
  companyId: string;
  initials: string;
  color: string;
  companyLogo?: string;
  category: string;
  city: string;
  locality: string;
  pincode: string;
  lat: number;
  lng: number;
  distanceKm: number;
  distanceFromSearch?: boolean;
  salaryMin: number;
  salaryMax: number;
  salaryType: "monthly";
  incentiveMax: number;
  openings: number;
  immediateJoining: boolean;
  vehicle: "Bike required" | "EV accepted" | "No vehicle required";
  verified: boolean;
  employmentType: "Full-time" | "Part-time" | "Flexible";
  shift: "Morning" | "Evening" | "Night" | "Flexible";
  postedAt: string;
  description: string;
  requirements: string[];
  status?: "Pending approval" | "Active" | "Paused" | "Rejected" | "Expired";
  showEverywhere?: boolean;
};
export type Application = {
  id: string;
  jobId: string;
  name: string;
  mobile: string;
  pincode: string;
  bike: string;
  licence: string;
  joining: string;
  status: "Applied" | "Contacted" | "Interview" | "Selected" | "Joined";
  createdAt: string;
};
export type PostedJob = {
  id: string;
  title: string;
  category: string;
  openings: number;
  state: string;
  district: string;
  city: string;
  pincode: string;
  locality: string;
  radius: string;
  salaryMin: number;
  salaryMax: number;
  incentives: string;
  salaryType: string;
  employmentType: string;
  vehicle: string;
  experience: string;
  shift: string;
  joining: string;
  description: string;
  status: "Pending approval" | "Active" | "Paused" | "Rejected" | "Expired";
  createdAt: string;
};
export type SearchFilters = {
  location?: string;
  category?: string;
  radius?: string;
  salary?: string;
  type?: string;
  vehicle?: string;
  shift?: string;
  immediate?: boolean;
};
